apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bb1.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "bb1.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  # this becomes /app/config.json in the container
  bb1.conf: |-
    {
      "port": {{ .Values.service.port }},
      "poll_ms": {{ .Values.config.poll_ms }},
      "backup_poll_ms1": {{ .Values.config.backup_poll_ms1 }},
      "backup_poll_ms2": {{ .Values.config.backup_poll_ms2 }},
      "ema_window": {{ .Values.config.ema_window }},
      {{- with .Values.config.redis }}
      "redis_url": {{ printf "redis://%s-%s:%d/%d" (include "bb1.fullname" $) .host (.port|int) (.db|int) | toJson }},
      {{- end }}
      "snapshot_sec": {{ .Values.config.snapshot_sec }},
      "log_level": "{{ .Values.config.log_level }}",
      "coingecko_api_key": "{{ .Values.config.coingeckoApiKey }}",
      "coingecko_key_type": "{{ .Values.config.coingeckoKeyType }}"
    }
