// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "Returns 200 if service is healthy",
                "tags": [
                    "probes"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Exposes Prometheus-compatible metrics",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Prometheus metrics",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/ratio": {
            "get": {
                "description": "Returns the EMA-based fair price ratio, spot price, and sigma",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ratio"
                ],
                "summary": "Get fair price ratio",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.RatioResponse"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Returns 200 if service is ready",
                "tags": [
                    "probes"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "main.RatioResponse": {
            "type": "object",
            "properties": {
                "fair": {
                    "type": "number"
                },
                "sigma": {
                    "type": "number"
                },
                "spot": {
                    "type": "number"
                },
                "updated": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
